name: Deploy AWS Lambda Function

on:
  push:
    branches:
      - main

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # 替换为您的 AWS 区域

      - name: Package Lambda function code
        run: |
          npm install # 安装依赖项，确保您的 package.json 文件在仓库根目录下
          zip -r function.zip . # 打包您的 Lambda 函数代码和依赖项

      - name: Deploy Lambda function
        run: |
          set +e
          function_exists=$(aws lambda get-function --function-name demo-github 2>&1)
          if echo "${function_exists}" | grep -q 'ResourceNotFoundException'; then
            echo "Function does not exist, creating..."
            aws lambda create-function --function-name demo-github \
              --runtime nodejs14.x \
              --role arn:aws:iam::462445180795:role/MyLambdaRole \ # 使用您的实际角色 ARN
              --handler index.handler \ # 确保此处与您的入口点匹配
              --zip-file fileb://function.zip
          else
            echo "Function exists, updating..."
            aws lambda update-function-code --function-name demo-github \
              --zip-file fileb://function.zip
          fi
          set -e
